### ISSUE TITLE
Python 3 encoding issue `UnicodeDecodeError` and a possible way of getting around 

### ISSUE THREAD

**Issue by Vimos** [alpv95/MemeProject#2]
I am facing an `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte`  error, when I am running in `python 3.6`.
```
Traceback (most recent call last):
  File "/home/vimos/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/vimos/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "build_mscoco_data.py", line 279, in _process_image_files
    sequence_example = _to_sequence_example(image, decoder, vocab)
  File "build_mscoco_data.py", line 215, in _to_sequence_example
    encoded_image = f.read()
  File "/home/vimos/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 127, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length, status))
  File "/home/vimos/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 95, in _prepare_value
    return compat.as_str_any(val)
  File "/home/vimos/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 113, in as_str_any
    return as_str(value)
  File "/home/vimos/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 86, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```
I found a way to get around error after applying the following patch:
```
index 2c3e9d9..ef27b7e 100755
--- a/im2txt/data/build_mscoco_data.py
+++ b/im2txt/data/build_mscoco_data.py
@@ -187,7 +187,8 @@ def _int64_feature(value):
 
 def _bytes_feature(value):
   """Wrapper for inserting a bytes Feature into a SequenceExample proto."""
-  return tf.train.Feature(bytes_list=tf.train.BytesList(value=[str(value)]))
+  value = value if type(value) == bytes else bytes(value, encoding='utf8')
+  return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))
 
 
 def _int64_feature_list(values):
@@ -211,7 +212,8 @@ def _to_sequence_example(image, decoder, vocab):
   Returns:
     A SequenceExample proto.
   """
-  with tf.gfile.FastGFile(image.filename, "r") as f:
+  with tf.gfile.FastGFile(image.filename, "rb") as f:
     encoded_image = f.read()
```
I hope this makes sense, just in case I'm making mistakes due to not familiar with the `tensorflow` apis.

**Comment by ShawDa** [comment]
Thanks~
